version: '2.3'
services:

  #PHP Service
  app:
    build: ./app
    container_name: app
    working_dir: /application
    # volumes:
    #   - ./app/:/var/www
    networks:
      - app-network
    environment:
      - DB_DATABASE=laravel
      - DB_PASSWORD=root
      - DB_USERNAME=root
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy

  #Nginx Service
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./app/:/var/www
    networks:
      - app-network

  #Redis Service
  redis:
    image: redis:alpine
    expose:
      - 6379
  

  #MySQL Service
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "33600:3306"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql/conf.d:/etc/mysql/conf.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", 'mysql -uroot --database=laravel --password=root --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
      interval: 10s
      timeout: 10s
      retries: 4

networks:
  app-network:
    driver: bridge
